export const ErrorCodes = {
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  BAD_REQUEST: "BAD_REQUEST",
  TENANT_MISMATCH: "TENANT_MISMATCH",
  OUT_OF_SCOPE: "OUT_OF_SCOPE",
  BUDGET_EXCEEDED: "BUDGET_EXCEEDED",
  SANDBOX_ERROR: "SANDBOX_ERROR",
  TOOL_VALIDATION_ERROR: "TOOL_VALIDATION_ERROR",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
} as const;

export type ErrorCode = typeof ErrorCodes[keyof typeof ErrorCodes];
